"""add ats_postings, web_social_status, blog_status to kundali

Revision ID: 560c49369be7
Revises: bed3128a8df6
Create Date: 2026-09-23 12:49:49.653245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560c49369be7'
down_revision: Union[str, Sequence[str], None] = 'bed3128a8df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kundali', sa.Column('ats_postings', sa.JSON(), nullable=True))
    op.add_column('kundali', sa.Column('web_social_status', sa.JSON(), nullable=True))
    op.add_column('kundali', sa.Column('blog_status', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kundali', 'blog_status')
    op.drop_column('kundali', 'web_social_status')
    op.drop_column('kundali', 'ats_postings')
    # ### end Alembic commands ###
