"""rename recent_shifts to recenet_commits

Revision ID: a44f447a2934
Revises: 560c49369be7
Create Date: 2026-09-23 12:57:59.740416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a44f447a2934'
down_revision: Union[str, Sequence[str], None] = '560c49369be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kundali', sa.Column('recent_commits', sa.JSON(), nullable=True))
    op.drop_column('kundali', 'recent_shifts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kundali', sa.Column('recent_shifts', sqlite.JSON(), nullable=True))
    op.drop_column('kundali', 'recent_commits')
    # ### end Alembic commands ###
