"""add kundali table

Revision ID: bed3128a8df6
Revises: b5922e36556c
Create Date: 2026-08-16 09:06:51.394000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed3128a8df6'
down_revision: Union[str, Sequence[str], None] = 'b5922e36556c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kundali',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('focus_areas', sa.JSON(), nullable=True),
    sa.Column('cadence_baseline', sa.JSON(), nullable=True),
    sa.Column('recent_shifts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kundali')
    # ### end Alembic commands ###
